<?php

$post_available = [
    101 => ['cadre' => 'ADMN', 'total_post' => 5, 'MQ' => 3, 'CFF' => 1, 'EM' => 1, 'PHC' => 0],
    102 => ['cadre' => 'POLC', 'total_post' => 7,  'MQ' => 4,  'CFF' => 1, 'EM' => 1, 'PHC' => 1],
    103 => ['cadre' => 'FRGN', 'total_post' => 3, 'MQ' => 2, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    104 => ['cadre' => 'ACNT', 'total_post' => 9,  'MQ' => 8,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    105 => ['cadre' => 'TAXN', 'total_post' => 6,  'MQ' => 6,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    106 => ['cadre' => 'CUST', 'total_post' => 14, 'MQ' => 13, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    107 => ['cadre' => 'POST', 'total_post' => 8,  'MQ' => 7,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    108 => ['cadre' => 'RAIL', 'total_post' => 5,  'MQ' => 5,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    109 => ['cadre' => 'COOP', 'total_post' => 13, 'MQ' => 12, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    110 => ['cadre' => 'FOOD', 'total_post' => 10, 'MQ' => 9,  'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    111 => ['cadre' => 'ANSA', 'total_post' => 4,  'MQ' => 4,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    112 => ['cadre' => 'INFO', 'total_post' => 11, 'MQ' => 10, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    113 => ['cadre' => 'FAMP', 'total_post' => 16, 'MQ' => 15, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    114 => ['cadre' => 'STAT', 'total_post' => 7,  'MQ' => 7,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    115 => ['cadre' => 'ECON', 'total_post' => 3,  'MQ' => 3,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    116 => ['cadre' => 'TRAD', 'total_post' => 12, 'MQ' => 11, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    117 => ['cadre' => 'LBWA', 'total_post' => 5,  'MQ' => 5,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    201 => ['cadre' => 'HLTH', 'total_post' => 14, 'MQ' => 13, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    202 => ['cadre' => 'AGRI', 'total_post' => 10, 'MQ' => 9,  'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    203 => ['cadre' => 'FISH', 'total_post' => 7,  'MQ' => 7,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    204 => ['cadre' => 'ANML', 'total_post' => 11, 'MQ' => 10, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    205 => ['cadre' => 'FDNT', 'total_post' => 16, 'MQ' => 15, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    206 => ['cadre' => 'STTC', 'total_post' => 5,  'MQ' => 5,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    207 => ['cadre' => 'EDUC', 'total_post' => 19, 'MQ' => 18, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    208 => ['cadre' => 'ROME', 'total_post' => 12, 'MQ' => 11, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    209 => ['cadre' => 'ENPH', 'total_post' => 2,  'MQ' => 1,  'CFF' => 0, 'EM' => 1, 'PHC' => 0],
    210 => ['cadre' => 'ENPW', 'total_post' => 14, 'MQ' => 13, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    211 => ['cadre' => 'ENWD', 'total_post' => 8,  'MQ' => 7,  'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    212 => ['cadre' => 'ARCH', 'total_post' => 6,  'MQ' => 6,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    213 => ['cadre' => 'FORE', 'total_post' => 17, 'MQ' => 16, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    214 => ['cadre' => 'TXTL', 'total_post' => 9,  'MQ' => 8,  'CFF' => 1, 'EM' => 0, 'PHC' => 0],
];
