<?php

$post_available = [
    101 => ['cadre' => 'ADMN', 'total_post' => 3, 'MQ' => 2, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    102 => ['cadre' => 'POLC', 'total_post' => 3,  'MQ' => 2,  'CFF' => 0, 'EM' => 1, 'PHC' => 0],
    103 => ['cadre' => 'FRGN', 'total_post' => 2, 'MQ' => 2, 'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    105 => ['cadre' => 'TAXN', 'total_post' => 2,  'MQ' => 2,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    106 => ['cadre' => 'CUST', 'total_post' => 2, 'MQ' => 1, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    107 => ['cadre' => 'POST', 'total_post' => 1,  'MQ' => 1,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    108 => ['cadre' => 'RAIL', 'total_post' => 5,  'MQ' => 4,  'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    109 => ['cadre' => 'COOP', 'total_post' => 2, 'MQ' => 2, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    111 => ['cadre' => 'ANSA', 'total_post' => 4,  'MQ' => 2,  'CFF' => 1, 'EM' => 1, 'PHC' => 0],
    112 => ['cadre' => 'INFO', 'total_post' => 3, 'MQ' => 2, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    113 => ['cadre' => 'FAMP', 'total_post' => 3, 'MQ' => 3, 'CFF' =>0, 'EM' => 0, 'PHC' => 0],
    115 => ['cadre' => 'ECON', 'total_post' => 3,  'MQ' => 3,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    116 => ['cadre' => 'TRAD', 'total_post' => 2, 'MQ' => 1, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    201 => ['cadre' => 'HLTH', 'total_post' => 3, 'MQ' => 2, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    202 => ['cadre' => 'AGRI', 'total_post' => 3, 'MQ' => 2,  'CFF' => 0, 'EM' => 0, 'PHC' => 1],
    203 => ['cadre' => 'FISH', 'total_post' => 7,  'MQ' => 4,  'CFF' => 1, 'EM' => 1, 'PHC' => 1], 
    207 => ['cadre' => 'EDUC', 'total_post' => 2, 'MQ' => 1, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    208 => ['cadre' => 'ROME', 'total_post' => 2, 'MQ' => 2, 'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    209 => ['cadre' => 'ENPH', 'total_post' => 2,  'MQ' => 1,  'CFF' => 0, 'EM' => 1, 'PHC' => 0],
    210 => ['cadre' => 'ENPW', 'total_post' => 2, 'MQ' => 2, 'CFF' => 0, 'EM' => 0, 'PHC' => 0],
    213 => ['cadre' => 'FORE', 'total_post' => 2, 'MQ' => 1, 'CFF' => 1, 'EM' => 0, 'PHC' => 0],
    214 => ['cadre' => 'TXTL', 'total_post' => 2,  'MQ' => 2,  'CFF' => 0, 'EM' => 0, 'PHC' => 0],
];
